/*
 * Copyright 2021-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.trustworks.essentials.examples.webshop.sales.views.products_for_sale

import dk.trustworks.essentials.types.Amount
import dk.trustworks.essentials.examples.webshop.config.MoneyAttributeConverter
import jakarta.persistence.Column
import jakarta.persistence.Convert
import jakarta.persistence.Entity
import jakarta.persistence.Id
import jakarta.persistence.Table
import java.time.OffsetDateTime

/**
 * One row per product that is for sale: the answer to "what can I buy, and what does it cost?", shaped so the
 * query is `select * from products_for_sale_view` and nothing more.
 *
 * Nothing here is authoritative. Delete the table and it comes back by replaying the `Products` streams, which is
 * also how a new column gets filled in for products that were added years ago.
 *
 * [version] is the event's `EventOrder` within the product's stream - the position of the last event applied to
 * this row. It is what makes the projection idempotent: see the projector.
 *
 * The no-argument constructor Hibernate needs is generated by the Kotlin `jpa` compiler plugin (configured in
 * this module's POM), not written out. `Amount` names [MoneyAttributeConverter] explicitly: the framework's own
 * `AmountAttributeConverter` would store the price as a floating-point double, and that class explains why this
 * one exists instead.
 */
@Entity
@Table(name = "products_for_sale_view")
data class ProductForSaleView(
    @Id
    @Column(name = "product_id")
    val id: String,

    var name: String,

    @Convert(converter = MoneyAttributeConverter::class)
    @Column(precision = 19, scale = 2)
    var price: Amount,

    var version: Long,

    var lastUpdated: OffsetDateTime
)
