<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.1.0</version>
        <relativePath/>
    </parent>
    <groupId>com.example.twin</groupId>
    <artifactId>twin</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <properties>
        <java.version>26</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-webflux</artifactId>
        </dependency>
        <dependency>
            <groupId>dk.trustworks.essentials.components</groupId>
            <artifactId>spring-boot-starter-postgresql</artifactId>
            <version>DEV-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>dk.trustworks.essentials.components</groupId>
            <artifactId>spring-boot-starter-mongodb</artifactId>
            <version>DEV-SNAPSHOT</version>
        </dependency>
        <dependency>
            <groupId>dk.trustworks.essentials</groupId>
            <artifactId>types-spring-web</artifactId>
            <version>DEV-SNAPSHOT</version>
        </dependency>
    </dependencies>
    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.springdoc</groupId>
                <artifactId>springdoc-openapi-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>
</project>
