/*
 * Copyright 2021-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.trustworks.essentials.components.eventsourced.aggregates.snapshot;

import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.ConfigurableEventStore;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.eventstream.*;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.persistence.AggregateEventStreamConfiguration;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.serializer.json.JSONEventSerializer;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.types.EventOrder;
import dk.trustworks.essentials.components.foundation.postgresql.PostgresqlUtil;
import dk.trustworks.essentials.components.foundation.transaction.jdbi.*;
import dk.trustworks.essentials.shared.collections.Lists;
import io.micrometer.core.instrument.MeterRegistry;
import org.slf4j.*;

import java.util.*;
import java.util.stream.Collectors;

import static dk.trustworks.essentials.shared.FailFast.requireNonNull;


/**
 * Postgresql specific version of {@link AggregateSnapshotRepository}
 *
 * <u><b>Security</b></u><br>
 * The user can supply a custom {@code snapshotTableName}, which controls the name of the table where {@link AggregateSnapshot}'s will be stored<br>
 * <br>
 * To support customization of storage table name, the {@code snapshotTableName} will be directly used in constructing SQL statements
 * through string concatenation, which exposes the component to SQL injection attacks.<br>
 * <br>
 * <b>It is the responsibility of the user of this component to sanitize the {@code snapshotTableName}
 * to ensure the security of all the SQL statements generated by this component.</b><br>
 * The {@link PostgresqlAggregateSnapshotRepository} component will
 * call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
 * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
 * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
 * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes</b>.<br>
 * Users must ensure thorough sanitization and validation of API input parameters, values, column names, function names, table names, and index names.<br>
 * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
 * It is highly recommended that the {@code snapshotTableName} value is only derived from a controlled and trusted source.<br>
 * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code snapshotTableName} value.<br>
 * <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
 * vulnerabilities, compromising the security and integrity of the database.</b>
 */
@SuppressWarnings("unchecked")
public class PostgresqlAggregateSnapshotRepository implements AggregateSnapshotRepository {
    private static final Logger log                                    = LoggerFactory.getLogger(dk.trustworks.essentials.components.eventsourced.aggregates.snapshot.PostgresqlAggregateSnapshotRepository.class);
    public static final  String DEFAULT_AGGREGATE_SNAPSHOTS_TABLE_NAME = "aggregate_snapshots";

    private final AggregateSnapshotStateAdapter                                       snapshotStateAdapter;
    private final AggregateSnapshotStore                                               snapshotStore;
    private final AggregateSnapshotMeasurementSupport                                 measurementSupport;
    private final AddNewAggregateSnapshotStrategy                                     addNewSnapshotStrategy;
    private final AggregateSnapshotDeletionStrategy                                   snapshotDeletionStrategy;

    /**
     * Create a new durable Postgresql version of the {@link PostgresqlAggregateSnapshotRepository}
     * that will persist {@link AggregateSnapshot}'s into the {@link #DEFAULT_AGGREGATE_SNAPSHOTS_TABLE_NAME} table<br>
     * Adding new {@link AggregateSnapshot}'s when it's behind by 10 events AND
     * Deleting All Historic {@link AggregateSnapshot}'s
     *
     * @param eventStore        the event store responsible for persisting aggregate event stream
     * @param unitOfWorkFactory unit of work factory for controlling transactions
     * @param jsonSerializer    JSON serializer that will be used to serialize Aggregate instances
     */
    public PostgresqlAggregateSnapshotRepository(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore,
                                                 HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory,
                                                 JSONEventSerializer jsonSerializer) {
        this(eventStore,
             unitOfWorkFactory,
             Optional.empty(),
             jsonSerializer,
             AddNewAggregateSnapshotStrategy.updateWhenBehindByNumberOfEvents(10),
             AggregateSnapshotDeletionStrategy.deleteAllHistoricSnapshots());
    }

    /**
     * Create a new durable Postgresql version of the {@link PostgresqlAggregateSnapshotRepository}<br>
     * Adding new {@link AggregateSnapshot}'s when it's behind by 10 events AND
     * Deleting All Historic {@link AggregateSnapshot}'s
     *
     * @param eventStore        the event store responsible for persisting aggregate event stream
     * @param unitOfWorkFactory unit of work factory for controlling transactions
     * @param snapshotTableName the name of the table where {@link AggregateSnapshot}'s will be stored<br>
     *                          <strong>Note:</strong><br>
     *                          To support customization of storage table name, the {@code snapshotTableName} will be directly used in constructing SQL statements
     *                          through string concatenation, which exposes the component to SQL injection attacks.<br>
     *                          <br>
     *                          <strong>Security Note:</strong><br>
     *                          <b>It is the responsibility of the user of this component to sanitize the {@code snapshotTableName}
     *                          to ensure the security of all the SQL statements generated by this component.</b><br>
     *                          The {@link PostgresqlAggregateSnapshotRepository} component will
     *                          call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                          The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                          However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                          <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes</b>.<br>
     *                          Users must ensure thorough sanitization and validation of API input parameters, values, column names, function names, table names, and index names.<br>
     *                          Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *                          It is highly recommended that the {@code snapshotTableName} value is only derived from a controlled and trusted source.<br>
     *                          To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code snapshotTableName} value.<br>
     *                          <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                          vulnerabilities, compromising the security and integrity of the database.</b>
     * @param jsonSerializer    JSON serializer that will be used to serialize Aggregate instances
     */
    public PostgresqlAggregateSnapshotRepository(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore,
                                                 HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory,
                                                 String snapshotTableName,
                                                 JSONEventSerializer jsonSerializer) {
        this(eventStore,
             unitOfWorkFactory,
             Optional.ofNullable(snapshotTableName),
             jsonSerializer,
             AddNewAggregateSnapshotStrategy.updateWhenBehindByNumberOfEvents(10),
             AggregateSnapshotDeletionStrategy.deleteAllHistoricSnapshots());
    }

    /**
     * Create a new durable Postgresql version of the {@link PostgresqlAggregateSnapshotRepository}
     *
     * @param eventStore               the event store responsible for persisting aggregate event stream
     * @param unitOfWorkFactory        unit of work factory for controlling transactions
     * @param snapshotTableName        the name of the table where {@link AggregateSnapshot}'s will be stored<br>
     *                                 <strong>Note:</strong><br>
     *                                 To support customization of storage table name, the {@code snapshotTableName} will be directly used in constructing SQL statements
     *                                 through string concatenation, which exposes the component to SQL injection attacks.<br>
     *                                 <br>
     *                                 <strong>Security Note:</strong><br>
     *                                 <b>It is the responsibility of the user of this component to sanitize the {@code snapshotTableName}
     *                                 to ensure the security of all the SQL statements generated by this component.</b><br>
     *                                 The {@link PostgresqlAggregateSnapshotRepository} component will
     *                                 call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                                 The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                 However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                 <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes</b>.<br>
     *                                 Users must ensure thorough sanitization and validation of API input parameters, values, column names, function names, table names, and index names.<br>
     *                                 Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *                                 It is highly recommended that the {@code snapshotTableName} value is only derived from a controlled and trusted source.<br>
     *                                 To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code snapshotTableName} value.<br>
     *                                 <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                                 vulnerabilities, compromising the security and integrity of the database.</b>
     * @param addNewSnapshotStrategy   the strategy determining when a new {@link AggregateSnapshot} will be stored
     * @param snapshotDeletionStrategy the strategy determining when an existing {@link AggregateSnapshot} will be deleted
     * @deprecated Use {@link #builder()}. This constructor declares an {@code Optional} parameter and/or more than five parameters; the builder names every argument and accepts both plain values and {@code Optional}s. It is unchanged and remains the implementation the builder delegates to.
     */
    @Deprecated(forRemoval = true, since = "0.40.x")
    public PostgresqlAggregateSnapshotRepository(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore,
                                                 HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory,
                                                 String snapshotTableName,
                                                 JSONEventSerializer jsonSerializer,
                                                 AddNewAggregateSnapshotStrategy addNewSnapshotStrategy,
                                                 AggregateSnapshotDeletionStrategy snapshotDeletionStrategy) {
        this(eventStore,
             unitOfWorkFactory,
             Optional.ofNullable(snapshotTableName),
             jsonSerializer,
             addNewSnapshotStrategy,
             snapshotDeletionStrategy);
    }

    /**
     * Create a new durable Postgresql version of the {@link PostgresqlAggregateSnapshotRepository}
     * that will persist {@link AggregateSnapshot}'s into the {@link #DEFAULT_AGGREGATE_SNAPSHOTS_TABLE_NAME} table
     *
     * @param eventStore               the event store responsible for persisting aggregate event stream
     * @param unitOfWorkFactory        unit of work factory for controlling transactions
     * @param jsonSerializer           JSON serializer that will be used to serialize Aggregate instances
     * @param addNewSnapshotStrategy   the strategy determining when a new {@link AggregateSnapshot} will be stored
     * @param snapshotDeletionStrategy the strategy determining when an existing {@link AggregateSnapshot} will be deleted
     */
    public PostgresqlAggregateSnapshotRepository(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore,
                                                 HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory,
                                                 JSONEventSerializer jsonSerializer,
                                                 AddNewAggregateSnapshotStrategy addNewSnapshotStrategy,
                                                 AggregateSnapshotDeletionStrategy snapshotDeletionStrategy) {
        this(eventStore,
             unitOfWorkFactory,
             Optional.empty(),
             jsonSerializer,
             addNewSnapshotStrategy,
             snapshotDeletionStrategy);
    }

    /**
     * Create a new durable Postgresql version of the {@link PostgresqlAggregateSnapshotRepository}
     *
     * @param eventStore               the event store responsible for persisting aggregate event stream
     * @param unitOfWorkFactory        unit of work factory for controlling transactions
     * @param snapshotTableName        the name of the table where {@link AggregateSnapshot}'s will be stored<br>
     *                                 <strong>Note:</strong><br>
     *                                 To support customization of storage table name, the {@code snapshotTableName} will be directly used in constructing SQL statements
     *                                 through string concatenation, which exposes the component to SQL injection attacks.<br>
     *                                 <br>
     *                                 <strong>Security Note:</strong><br>
     *                                 <b>It is the responsibility of the user of this component to sanitize the {@code snapshotTableName}
     *                                 to ensure the security of all the SQL statements generated by this component.</b><br>
     *                                 The {@link PostgresqlAggregateSnapshotRepository} component will
     *                                 call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                                 The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                                 However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                                 <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes</b>.<br>
     *                                 Users must ensure thorough sanitization and validation of API input parameters, values, column names, function names, table names, and index names.<br>
     *                                 Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *                                 It is highly recommended that the {@code snapshotTableName} value is only derived from a controlled and trusted source.<br>
     *                                 To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code snapshotTableName} value.<br>
     *                                 <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                                 vulnerabilities, compromising the security and integrity of the database.</b>
     * @param jsonSerializer           JSON serializer that will be used to serialize Aggregate instances
     * @param addNewSnapshotStrategy   the strategy determining when a new {@link AggregateSnapshot} will be stored
     * @param snapshotDeletionStrategy the strategy determining when an existing {@link AggregateSnapshot} will be deleted
     * @deprecated Use {@link #builder()}. This constructor declares an {@code Optional} parameter and/or more than five parameters; the builder names every argument and accepts both plain values and {@code Optional}s. It is unchanged and remains the implementation the builder delegates to.
     */
    @Deprecated(forRemoval = true, since = "0.40.x")
    public PostgresqlAggregateSnapshotRepository(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore,
                                                 HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory,
                                                 Optional<String> snapshotTableName,
                                                 JSONEventSerializer jsonSerializer,
                                                 AddNewAggregateSnapshotStrategy addNewSnapshotStrategy,
                                                 AggregateSnapshotDeletionStrategy snapshotDeletionStrategy) {
        this(eventStore,
             unitOfWorkFactory,
             snapshotTableName,
             jsonSerializer,
             addNewSnapshotStrategy,
             snapshotDeletionStrategy,
             Optional.empty());
    }

    @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
    /**
     * @deprecated Use {@link #builder()}. This constructor declares an {@code Optional} parameter and/or more than five parameters; the builder names every argument and accepts both plain values and {@code Optional}s. It is unchanged and remains the implementation the builder delegates to.
     */
    @Deprecated(forRemoval = true, since = "0.40.x")
    public PostgresqlAggregateSnapshotRepository(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore,
                                                 HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory,
                                                 Optional<String> snapshotTableName,
                                                 JSONEventSerializer jsonSerializer,
                                                 AddNewAggregateSnapshotStrategy addNewSnapshotStrategy,
                                                 AggregateSnapshotDeletionStrategy snapshotDeletionStrategy,
                                                 Optional<MeterRegistry> meterRegistryOptional) {
        this.snapshotStateAdapter = new DefaultAggregateSnapshotStateAdapter(requireNonNull(jsonSerializer, "No jsonSerializer instance provided"));
        this.snapshotStore = new PostgresqlAggregateSnapshotStore(eventStore,
                                                                  unitOfWorkFactory,
                                                                  snapshotTableName,
                                                                  jsonSerializer,
                                                                  meterRegistryOptional);
        this.measurementSupport = new AggregateSnapshotMeasurementSupport(meterRegistryOptional);
        this.addNewSnapshotStrategy = requireNonNull(addNewSnapshotStrategy, "No snapshotUpdateStrategy instance provided");
        this.snapshotDeletionStrategy = requireNonNull(snapshotDeletionStrategy, "No snapshotDeletionStrategy instance provided");
    }

    @Override
    public <ID, AGGREGATE_IMPL_TYPE> Optional<AggregateSnapshot<ID, AGGREGATE_IMPL_TYPE>> loadSnapshot(AggregateType aggregateType,
                                                                                                       ID aggregateId,
                                                                                                       EventOrder withLastIncludedEventOrderLessThanOrEqualTo,
                                                                                                       Class<AGGREGATE_IMPL_TYPE> aggregateImplType) {
        return snapshotStore.loadSnapshot(aggregateType,
                                          aggregateId,
                                          withLastIncludedEventOrderLessThanOrEqualTo,
                                          aggregateImplType);
    }

    @Override
    public <ID, AGGREGATE_IMPL_TYPE> void aggregateUpdated(AGGREGATE_IMPL_TYPE aggregate, AggregateEventStream<ID> persistedEvents) {
        requireNonNull(aggregate, "No aggregate instance supplied");
        requireNonNull(persistedEvents, "No persistedEvents stream supplied");
        var aggregateType = persistedEvents.aggregateType();
        var aggregateImplType = (Class<AGGREGATE_IMPL_TYPE>) aggregate.getClass();
        var mostRecentlyStoredSnapshotLastIncludedEventOrder = snapshotStore.findMostRecentLastIncludedEventOrder(aggregateType,
                                                                                                                   persistedEvents.aggregateId(),
                                                                                                                   aggregateImplType);
        if (shouldWeAddANewAggregateSnapshot(aggregate, persistedEvents, aggregateType, aggregateImplType.getName(), mostRecentlyStoredSnapshotLastIncludedEventOrder)) {
            var lastAppliedEventOrder = Lists.last(persistedEvents.eventList()).get().eventOrder();
            deleteHistoricSnapShotsIfNecessary(aggregate, persistedEvents, aggregateType, aggregateImplType, lastAppliedEventOrder);

            snapshotStore.saveSnapshot(aggregateType,
                                       persistedEvents.aggregateId(),
                                       aggregateImplType,
                                       lastAppliedEventOrder,
                                       measurementSupport.recordSerializeSnapshot(aggregateType,
                                                                                  aggregateImplType,
                                                                                  () -> snapshotStateAdapter.serializeSnapshotState(aggregate)));
        }
    }

    private <ID, AGGREGATE_IMPL_TYPE> boolean shouldWeAddANewAggregateSnapshot(AGGREGATE_IMPL_TYPE aggregate, AggregateEventStream<ID> persistedEvents, AggregateType aggregateType, String aggregateImplType, Optional<EventOrder> mostRecentlyStoredSnapshotLastIncludedEventOrder) {
        if (addNewSnapshotStrategy.shouldANewAggregateSnapshotBeAdded(aggregate, persistedEvents, mostRecentlyStoredSnapshotLastIncludedEventOrder)) {
            if (log.isDebugEnabled()) {
                log.debug("[{}:{}] {} strategy determined to ADD a new Aggregate Snapshot for '{}' based on mostRecentlyStoredSnapshotLastIncludedEventOrder {} and persistedEvents->eventOrders: {}",
                          aggregateType,
                          persistedEvents.aggregateId(),
                          addNewSnapshotStrategy,
                          aggregateImplType,
                          mostRecentlyStoredSnapshotLastIncludedEventOrder,
                          persistedEvents.eventList().stream().map(persistedEvent -> persistedEvent.eventOrder().longValue()).collect(Collectors.toList()));
            }
            return true;
        } else {
            if (log.isDebugEnabled()) {
                log.debug("[{}:{}] {} strategy determined NOT to add a new Aggregate Snapshot for '{}' based on mostRecentlyStoredSnapshotLastIncludedEventOrder {} and persistedEvents->eventOrders: {}",
                          aggregateType,
                          persistedEvents.aggregateId(),
                          addNewSnapshotStrategy,
                          aggregateImplType,
                          mostRecentlyStoredSnapshotLastIncludedEventOrder,
                          persistedEvents.eventList().stream().map(persistedEvent -> persistedEvent.eventOrder().longValue()).collect(Collectors.toList()));
            }
            return false;
        }
    }

    private <ID, AGGREGATE_IMPL_TYPE> void deleteHistoricSnapShotsIfNecessary(AGGREGATE_IMPL_TYPE aggregate,
                                                                              AggregateEventStream<ID> persistedEvents,
                                                                              AggregateType aggregateType,
                                                                              Class<AGGREGATE_IMPL_TYPE> aggregateImplType,
                                                                              EventOrder lastAppliedEventOrder) {
        if (snapshotDeletionStrategy.requiresExistingSnapshotDetailsToDetermineWhichAggregateSnapshotsToDelete()) {
            var existingSnapshots = snapshotStore.loadAllSnapshots(aggregateType,
                                                                   persistedEvents.aggregateId(),
                                                                   aggregateImplType,
                                                                   false);
            if (log.isDebugEnabled()) {
                log.debug("[{}:{}] Found {} {}'s Aggregate-Snapshots with eventOrderOfLastIncludedEvent: {}",
                          aggregateType,
                          persistedEvents.aggregateId(),
                          existingSnapshots.size(),
                          aggregateImplType.getName(),
                          existingSnapshots.stream().map(snapshot -> snapshot.eventOrderOfLastIncludedEvent.longValue()).collect(Collectors.toList()));
            }

            if (!existingSnapshots.isEmpty()) {
                var snapshotEventOrdersToDeleteStream = snapshotDeletionStrategy.resolveSnapshotsToDelete(existingSnapshots);
                var eventOrdersToDelete               = snapshotEventOrdersToDeleteStream.map(snapshot -> snapshot.eventOrderOfLastIncludedEvent).collect(Collectors.toList());
                if (!eventOrdersToDelete.isEmpty()) {
                    log.debug("[{}:{}] Will delete {} Historic {}'s Aggregate-Snapshots with eventOrderOfLastIncludedEvent: {}",
                              aggregateType,
                              persistedEvents.aggregateId(),
                              eventOrdersToDelete.size(),
                              aggregateImplType.getName(),
                              eventOrdersToDelete);

                    snapshotStore.deleteSnapshots(aggregateType,
                                                  persistedEvents.aggregateId(),
                                                  aggregateImplType,
                                                  eventOrdersToDelete);
                }
            }
        } else {
            snapshotStore.deleteSnapshotsOlderThan(aggregateType,
                                                   persistedEvents.aggregateId(),
                                                   aggregateImplType,
                                                   lastAppliedEventOrder);
        }
    }

    @Override
    public <ID, AGGREGATE_IMPL_TYPE> List<AggregateSnapshot<ID, AGGREGATE_IMPL_TYPE>> loadAllSnapshots(AggregateType aggregateType,
                                                                                                       ID aggregateId,
                                                                                                       Class<AGGREGATE_IMPL_TYPE> aggregateImplType,
                                                                                                       boolean includeSnapshotPayload) {
        return snapshotStore.loadAllSnapshots(aggregateType,
                                              aggregateId,
                                              aggregateImplType,
                                              includeSnapshotPayload);
    }

    @Override
    public <AGGREGATE_IMPL_TYPE> void deleteAllSnapshots(Class<AGGREGATE_IMPL_TYPE> ofAggregateImplementationType) {
        snapshotStore.deleteAllSnapshots(ofAggregateImplementationType);
    }

    @Override
    public <ID, AGGREGATE_IMPL_TYPE> void deleteSnapshots(AggregateType aggregateType, ID aggregateId, Class<AGGREGATE_IMPL_TYPE> withAggregateImplementationType) {
        snapshotStore.deleteSnapshots(aggregateType, aggregateId, withAggregateImplementationType);
    }

    @Override
    public <ID, AGGREGATE_IMPL_TYPE> void deleteSnapshots(AggregateType aggregateType,
                                                          ID aggregateId,
                                                          Class<AGGREGATE_IMPL_TYPE> withAggregateImplementationType,
                                                          List<EventOrder> snapshotEventOrdersToDelete) {
        snapshotStore.deleteSnapshots(aggregateType,
                                      aggregateId,
                                      withAggregateImplementationType,
                                      snapshotEventOrdersToDelete);
    }

    /**
     * Creates a builder for a {@link PostgresqlAggregateSnapshotRepository}.
     *
     * @return a new builder
     */
    public static Builder builder() {
        return new Builder();
    }

    /**
     * Builder for {@link PostgresqlAggregateSnapshotRepository}, obtained from {@link #builder()}.
     * <p>
     * The previously-{@code Optional} constructor parameters are plain nullable fields here, each with a
     * plain-value setter and an {@code Optional} overload for Spring {@code @Bean} methods.
     */
    public static final class Builder {
        private ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore;
        private HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory;
        private String snapshotTableName;
        private JSONEventSerializer jsonSerializer;
        private AddNewAggregateSnapshotStrategy addNewSnapshotStrategy;
        private AggregateSnapshotDeletionStrategy snapshotDeletionStrategy;
        private MeterRegistry meterRegistryOptional;

        /**
         * @param eventStore required
         * @return this builder
         */
        public Builder setEventStore(ConfigurableEventStore<? extends AggregateEventStreamConfiguration> eventStore) {
            this.eventStore = eventStore;
            return this;
        }

        /**
         * @param unitOfWorkFactory required
         * @return this builder
         */
        public Builder setUnitOfWorkFactory(HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory) {
            this.unitOfWorkFactory = unitOfWorkFactory;
            return this;
        }

        /**
         * @param snapshotTableName optional — {@code null} selects the default
         * @return this builder
         */
        public Builder setSnapshotTableName(String snapshotTableName) {
            this.snapshotTableName = snapshotTableName;
            return this;
        }

        /**
         * {@code Optional} overload of {@link #setSnapshotTableName(String)}.
         *
         * @param snapshotTableName the value, or empty for the default
         * @return this builder
         */
        @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
        public Builder setSnapshotTableName(Optional<String> snapshotTableName) {
            requireNonNull(snapshotTableName, "No snapshotTableName provided");
            return setSnapshotTableName(snapshotTableName.orElse(null));
        }

        /**
         * @param jsonSerializer required
         * @return this builder
         */
        public Builder setJsonSerializer(JSONEventSerializer jsonSerializer) {
            this.jsonSerializer = jsonSerializer;
            return this;
        }

        /**
         * @param addNewSnapshotStrategy required
         * @return this builder
         */
        public Builder setAddNewSnapshotStrategy(AddNewAggregateSnapshotStrategy addNewSnapshotStrategy) {
            this.addNewSnapshotStrategy = addNewSnapshotStrategy;
            return this;
        }

        /**
         * @param snapshotDeletionStrategy required
         * @return this builder
         */
        public Builder setSnapshotDeletionStrategy(AggregateSnapshotDeletionStrategy snapshotDeletionStrategy) {
            this.snapshotDeletionStrategy = snapshotDeletionStrategy;
            return this;
        }

        /**
         * @param meterRegistryOptional optional — {@code null} selects the default
         * @return this builder
         */
        public Builder setMeterRegistry(MeterRegistry meterRegistryOptional) {
            this.meterRegistryOptional = meterRegistryOptional;
            return this;
        }

        /**
         * {@code Optional} overload of {@link #setMeterRegistry(MeterRegistry)}.
         *
         * @param meterRegistryOptional the value, or empty for the default
         * @return this builder
         */
        @SuppressWarnings("OptionalUsedAsFieldOrParameterType")
        public Builder setMeterRegistry(Optional<MeterRegistry> meterRegistryOptional) {
            requireNonNull(meterRegistryOptional, "No meterRegistryOptional provided");
            return setMeterRegistry(meterRegistryOptional.orElse(null));
        }

        /**
         * @return the new {@link PostgresqlAggregateSnapshotRepository}
         */
        @SuppressWarnings("removal")
        public PostgresqlAggregateSnapshotRepository build() {
            return new PostgresqlAggregateSnapshotRepository(eventStore,
                                                             unitOfWorkFactory,
                                                             Optional.ofNullable(snapshotTableName),
                                                             jsonSerializer,
                                                             addNewSnapshotStrategy,
                                                             snapshotDeletionStrategy,
                                                             Optional.ofNullable(meterRegistryOptional));
        }
    }

}
