/*
 * Copyright 2021-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.persistence.table_per_aggregate_type;

import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.eventstream.*;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.serializer.AggregateIdSerializer;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.serializer.json.EssentialsJSONEventSerializers;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.test_data.OrderId;
import dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.transaction.*;
import dk.trustworks.essentials.components.foundation.postgresql.PostgresqlCreateSchemaApplier;
import dk.trustworks.essentials.components.foundation.schema.*;
import org.jdbi.v3.core.Jdbi;
import org.jdbi.v3.postgres.PostgresPlugin;
import org.junit.jupiter.api.*;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.*;

import java.util.List;

import static dk.trustworks.essentials.components.eventsourced.eventstore.postgresql.persistence.table_per_aggregate_type.SeparateTablePerAggregateTypeEventStreamConfigurationFactory.standardSingleTenantConfiguration;
import static org.assertj.core.api.Assertions.assertThat;

/**
 * Who creates the event-stream tables: the strategy itself as each AggregateType is registered
 * ({@link SchemaOwnership#COMPONENT}), or the schema harness - in its sweep for the types registered before it ran,
 * and through the attached sink for those registered after ({@link SchemaOwnership#HARNESS}).
 */
@Testcontainers
class SeparateTablePerAggregateTypeSchemaOwnershipIT {
    private static final AggregateType ORDERS   = AggregateType.of("Orders");
    private static final AggregateType PRODUCTS = AggregateType.of("Products");

    @Container
    private final PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:18.4")
            .withDatabaseName("schema-ownership-it")
            .withUsername("test-user")
            .withPassword("secret-password");

    private Jdbi                                              jdbi;
    private EventStoreUnitOfWorkFactory<EventStoreUnitOfWork> unitOfWorkFactory;

    @BeforeEach
    void setUp() {
        jdbi = Jdbi.create(postgres.getJdbcUrl(), postgres.getUsername(), postgres.getPassword());
        jdbi.installPlugin(new PostgresPlugin());
        unitOfWorkFactory = new EventStoreManagedUnitOfWorkFactory(jdbi);
    }

    @Test
    void component_ownership_creates_each_table_as_its_aggregate_type_is_registered_and_records_it() {
        var strategy = strategy(SchemaOwnership.COMPONENT);

        register(strategy, ORDERS);

        assertThat(tableExists("orders_events")).isTrue();
        assertThat(indexExists("orders_events_tenant")).isTrue();
        assertThat(ledgerEntries("orders_events")).containsExactlyInAnyOrder("event-stream-table", "event-stream-tenant-index");
    }

    @Test
    void harness_ownership_leaves_the_tables_to_the_harness_sweep_and_then_applies_later_registrations_through_it() {
        var strategy = strategy(SchemaOwnership.HARNESS);
        register(strategy, ORDERS);
        assertThat(tableExists("orders_events")).as("nothing is created before the harness runs").isFalse();

        new EssentialsSchemaHarness(new PostgresqlCreateSchemaApplier(jdbi), SchemaContext.empty(), List.of(strategy)).apply();
        assertThat(tableExists("orders_events")).isTrue();
        assertThat(ledgerEntries("orders_events")).containsExactlyInAnyOrder("event-stream-table", "event-stream-tenant-index");

        register(strategy, PRODUCTS);
        assertThat(tableExists("products_events")).as("a type registered after the harness ran reaches its applier").isTrue();
        assertThat(ledgerEntries("products_events")).containsExactlyInAnyOrder("event-stream-table", "event-stream-tenant-index");
    }

    @Test
    void a_table_created_before_the_harness_existed_is_adopted() {
        // What an 0.5x installation left behind: the table, without its ledger entry
        jdbi.useHandle(handle -> handle.execute("CREATE TABLE orders_events (global_order bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, aggregate_id uuid NOT NULL, event_order bigint NOT NULL, " +
                                                        "event_id uuid NOT NULL, caused_by_event_id uuid, correlation_id text, event_type text NOT NULL, event_revision text NOT NULL, " +
                                                        "timestamp TIMESTAMP WITH TIME ZONE NOT NULL, event_payload jsonb NOT NULL, event_metadata jsonb NOT NULL, tenant text, " +
                                                        "UNIQUE (aggregate_id, event_order), UNIQUE (event_id))"));

        register(strategy(SchemaOwnership.COMPONENT), ORDERS);

        assertThat(ledgerEntries("orders_events")).containsExactlyInAnyOrder("event-stream-table", "event-stream-tenant-index");
        assertThat(indexExists("orders_events_tenant")).isTrue();
    }

    @Test
    void a_reset_recreates_the_table_even_while_the_harness_has_yet_to_run() {
        var strategy = strategy(SchemaOwnership.HARNESS);
        register(strategy, ORDERS);

        strategy.resetEventStorageFor(ORDERS);

        assertThat(tableExists("orders_events")).isTrue();
    }

    private SeparateTablePerAggregateTypePersistenceStrategy strategy(SchemaOwnership ownership) {
        return SeparateTablePerAggregateTypePersistenceStrategy.builder()
                                                               .setJdbi(jdbi)
                                                               .setUnitOfWorkFactory(unitOfWorkFactory)
                                                               .setEventMapper((aggregateId, configuration, event, eventOrder) -> {
                                                                   throw new UnsupportedOperationException("no events are persisted");
                                                               })
                                                               .setAggregateEventStreamConfigurationFactory(standardSingleTenantConfiguration(aggregateType -> aggregateType + "_events",
                                                                                                                                              EventStreamTableColumnNames.defaultColumnNames(),
                                                                                                                                              EssentialsJSONEventSerializers.create(),
                                                                                                                                              IdentifierColumnType.UUID,
                                                                                                                                              JSONColumnType.JSONB))
                                                               .setSchemaOwnership(ownership)
                                                               .build();
    }

    private static void register(SeparateTablePerAggregateTypePersistenceStrategy strategy, AggregateType aggregateType) {
        strategy.addAggregateEventStreamConfiguration(aggregateType, AggregateIdSerializer.serializerFor(OrderId.class));
    }

    private boolean tableExists(String tableName) {
        return jdbi.withHandle(handle -> handle.createQuery("SELECT to_regclass(:name) IS NOT NULL").bind("name", tableName).mapTo(Boolean.class).one());
    }

    private boolean indexExists(String indexName) {
        return tableExists(indexName);
    }

    private List<String> ledgerEntries(String objectName) {
        return jdbi.withHandle(handle -> {
            if (!tableExists(PostgresqlCreateSchemaApplier.DEFAULT_SCHEMA_HISTORY_TABLE_NAME)) {
                return List.<String>of();
            }
            return handle.createQuery("SELECT change_id FROM essentials_schema_history WHERE module_id = :module AND object_name = :object")
                         .bind("module", SeparateTablePerAggregateTypePersistenceStrategy.MODULE_ID)
                         .bind("object", objectName)
                         .mapTo(String.class)
                         .list();
        });
    }
}
