/*
 * Copyright 2021-2026 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package dk.trustworks.essentials.components.queue.postgresql;

import dk.trustworks.essentials.components.foundation.json.*;
import dk.trustworks.essentials.components.foundation.messaging.queue.*;
import dk.trustworks.essentials.components.foundation.messaging.queue.operations.*;
import dk.trustworks.essentials.components.foundation.postgresql.*;
import dk.trustworks.essentials.components.foundation.transaction.*;
import dk.trustworks.essentials.components.foundation.transaction.jdbi.*;

import java.time.Duration;
import java.util.function.Function;

import static dk.trustworks.essentials.components.queue.postgresql.PostgresqlDurableQueues.DEFAULT_DURABLE_QUEUES_TABLE_NAME;

/**
 * <u>Security</u><br>
 * It is the responsibility of the user of this component to sanitize the {@link #setSharedQueueTableName(String)}
 * to ensure the security of all the SQL statements generated by this component. The {@link PostgresqlDurableQueues} component will
 * call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
 * The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
 * However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
 * <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
 * Users must ensure thorough sanitization and validation of API input parameters, values, column names, function names, table names, and index names.<br>
 * Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
 * <br>
 * It is highly recommended that the {@code sharedQueueTableName} value is only derived from a controlled and trusted source.<br>
 * To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code sharedQueueTableName} value.<br>
 * <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
 * vulnerabilities, compromising the security and integrity of the database.</b>
 */
public final class PostgresqlDurableQueuesBuilder {
    private HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory;
    private JSONSerializer                                                jsonSerializer;
    private String                                                        sharedQueueTableName         = DEFAULT_DURABLE_QUEUES_TABLE_NAME;
    private MultiTableChangeListener<TableChangeNotification>             multiTableChangeListener     = null;
    private Function<ConsumeFromQueue, QueuePollingOptimizer>             queuePollingOptimizerFactory = null;
    private TransactionalMode                                             transactionalMode            = TransactionalMode.SingleOperationTransaction;
    /**
     * Only used if {@link #transactionalMode} has value {@link TransactionalMode#SingleOperationTransaction}
     */
    private Duration                                                      messageHandlingTimeout       = Duration.ofSeconds(30);

    /**
     * Controls whether the PostgresqlDurableQueues should use the CentralizedMessageFetcher
     * for optimized message fetching. Default is true.
     */
    private boolean                                    useCentralizedMessageFetcher             = true;
    private Duration                                   centralizedMessageFetcherPollingInterval = Duration.ofMillis(20);
    private Function<QueueName, QueuePollingOptimizer> centralizedQueuePollingOptimizerFactory  = null;
    private boolean                                    useBatchedFetch                          = PostgresqlDurableQueues.DEFAULT_USE_BATCHED_FETCH;
    private int                                        batchedFetchSwitchThreshold              = PostgresqlDurableQueues.DEFAULT_BATCHED_FETCH_SWITCH_THRESHOLD;
    private boolean                                    useBatchedAcknowledgement                = false;
    private int                                        acknowledgementMaxBatchSize              = BatchedAcknowledgementSettings.DEFAULT_MAX_BATCH_SIZE;
    private Duration                                   acknowledgementFlushInterval             = BatchedAcknowledgementSettings.DEFAULT_FLUSH_INTERVAL;
    private OrderedMessageDuplicateStrategy            orderedMessageDuplicateStrategy          = OrderedMessageDuplicateStrategy.REJECT;
    private DurableQueueMessageObserver               messageObserver                          = DurableQueueMessageObserver.none();
    private boolean                                   useOrderedMessageCursor                  = false;
    private int                                        batchedFetchWarnRowsThreshold            = PostgresqlDurableQueues.DEFAULT_BATCHED_FETCH_WARN_ROWS_THRESHOLD;

    /**
     * Use the separate ordered/unordered fetch queries rather than the single unified query. Default is
     * {@code true} — see {@link #setUseOrderedUnorderedQuery(boolean)}.
     */
    private boolean useOrderedUnorderedQuery = PostgresqlDurableQueues.DEFAULT_USE_ORDERED_UNORDERED_QUERY;

    /**
     * @param unitOfWorkFactory the {@link UnitOfWorkFactory} needed to access the database
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setUnitOfWorkFactory(HandleAwareUnitOfWorkFactory<? extends HandleAwareUnitOfWork> unitOfWorkFactory) {
        this.unitOfWorkFactory = unitOfWorkFactory;
        return this;
    }

    /**
     * @param jsonSerializer Set the {@link JSONSerializer} that is used to serialize/deserialize message payloads.<br>
     *                       If not set, then {@link JacksonJSONSerializer} with the {@link DurableQueuesSerialization#createDefaultObjectMapper()} will be used
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setJsonSerializer(JSONSerializer jsonSerializer) {
        this.jsonSerializer = jsonSerializer;
        return this;
    }

    /**
     * @param sharedQueueTableName the name of the table that will contain all messages (across all {@link QueueName}'s)<br>
     *                             Default is {@link PostgresqlDurableQueues#DEFAULT_DURABLE_QUEUES_TABLE_NAME}<br>
     *                             <strong>Note:</strong><br>
     *                             To support customization of storage table name, the {@code sharedQueueTableName} will be directly used in constructing SQL statements
     *                             through string concatenation, which exposes the component to SQL injection attacks.<br>
     *                             <br>
     *                             <strong>Security Note:</strong><br>
     *                             It is the responsibility of the user of this component to sanitize the {@code sharedQueueTableName}
     *                             to ensure the security of all the SQL statements generated by this component. The {@link PostgresqlDurableQueues} component will
     *                             call the {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} method to validate the table name as a first line of defense.<br>
     *                             The {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} provides an initial layer of defense against SQL injection by applying naming conventions intended to reduce the risk of malicious input.<br>
     *                             However, Essentials components as well as {@link PostgresqlUtil#checkIsValidTableOrColumnName(String)} does not offer exhaustive protection, nor does it assure the complete security of the resulting SQL against SQL injection threats.<br>
     *                             <b>The responsibility for implementing protective measures against SQL Injection lies exclusively with the users/developers using the Essentials components and its supporting classes.</b><br>
     *                             Users must ensure thorough sanitization and validation of API input parameters, values, column names, function names, table names, and index names.<br>
     *                             Insufficient attention to these practices may leave the application vulnerable to SQL injection, potentially endangering the security and integrity of the database.<br>
     *                             <br>
     *                             It is highly recommended that the {@code sharedQueueTableName} value is only derived from a controlled and trusted source.<br>
     *                             To mitigate the risk of SQL injection attacks, external or untrusted inputs should never directly provide the {@code sharedQueueTableName} value.<br>
     *                             <b>Failure to adequately sanitize and validate this value could expose the application to SQL injection
     *                             vulnerabilities, compromising the security and integrity of the database.</b>
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setSharedQueueTableName(String sharedQueueTableName) {
        this.sharedQueueTableName = sharedQueueTableName;
        return this;
    }

    /**
     * @param multiTableChangeListener optional {@link MultiTableChangeListener} that allows {@link PostgresqlDurableQueues} to use {@link QueuePollingOptimizer}
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setMultiTableChangeListener(MultiTableChangeListener<TableChangeNotification> multiTableChangeListener) {
        this.multiTableChangeListener = multiTableChangeListener;
        return this;
    }

    /**
     * @param queuePollingOptimizerFactory optional {@link QueuePollingOptimizer} factory that creates a {@link QueuePollingOptimizer} per {@link ConsumeFromQueue} command -
     *                                     if set to null {@link PostgresqlDurableQueues#createQueuePollingOptimizerFor(ConsumeFromQueue)} is used instead
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setQueuePollingOptimizerFactory(Function<ConsumeFromQueue, QueuePollingOptimizer> queuePollingOptimizerFactory) {
        this.queuePollingOptimizerFactory = queuePollingOptimizerFactory;
        return this;
    }

    /**
     * @param messageHandlingTimeout Only required if <code>transactionalMode</code> is {@link TransactionalMode#SingleOperationTransaction}.<br>
     *                               The parameter defines the timeout for messages being delivered, but haven't yet been acknowledged.
     *                               After this timeout the message delivery will be reset and the message will again be a candidate for delivery<br>
     *                               Default is 30 seconds
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setMessageHandlingTimeout(Duration messageHandlingTimeout) {
        this.messageHandlingTimeout = messageHandlingTimeout;
        return this;
    }

    /**
     * @param transactionalMode The {@link TransactionalMode} for this {@link DurableQueues} instance. If set to {@link TransactionalMode#SingleOperationTransaction}
     *                          then the consumer MUST call the {@link DurableQueues#acknowledgeMessageAsHandled(AcknowledgeMessageAsHandled)} explicitly in a new {@link UnitOfWork}<br>
     *                          Note: The default consumer calls {@link DurableQueues#acknowledgeMessageAsHandled(AcknowledgeMessageAsHandled)} after successful message handling
     *                          Default value {@link TransactionalMode#SingleOperationTransaction}
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setTransactionalMode(TransactionalMode transactionalMode) {
        this.transactionalMode = transactionalMode;
        return this;
    }

    /**
     * Set whether to use the {@link CentralizedMessageFetcher} for optimized message fetching across multiple queues.
     * When enabled (default), the {@link PostgresqlDurableQueues} will use {@link CentralizedMessageFetcherDurableQueueConsumer}
     * instances to handle messages. When disabled, it will use the traditional {@link DefaultDurableQueueConsumer} instances.
     *
     * @param useCentralizedMessageFetcher true to use centralized fetching (default), false to use the legacy consumer approach
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setUseCentralizedMessageFetcher(boolean useCentralizedMessageFetcher) {
        this.useCentralizedMessageFetcher = useCentralizedMessageFetcher;
        return this;
    }

    /**
     * Set the polling interval for the {@link CentralizedMessageFetcher}.
     * This value determines how frequently the fetcher checks for new messages when none are immediately available.
     * Default value is 20 milliseconds.
     *
     * @param centralizedMessageFetcherPollingInterval the polling interval duration
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setCentralizedMessageFetcherPollingInterval(Duration centralizedMessageFetcherPollingInterval) {
        this.centralizedMessageFetcherPollingInterval = centralizedMessageFetcherPollingInterval;
        return this;
    }

    /**
     * Sets the factory responsible for creating {@link QueuePollingOptimizer} instances for each {@link QueueName}.
     *
     * @param centralizedQueuePollingOptimizerFactory a factory function that takes a {@link QueueName}
     *                                                and produces a corresponding {@link QueuePollingOptimizer}.
     *                                                This function allows customization of queue polling optimization
     *                                                strategies for individual queues.
     */
    public PostgresqlDurableQueuesBuilder setCentralizedQueuePollingOptimizerFactory(Function<QueueName, QueuePollingOptimizer> centralizedQueuePollingOptimizerFactory) {
        this.centralizedQueuePollingOptimizerFactory = centralizedQueuePollingOptimizerFactory;
        return this;
    }

    /**
     * Opt in to batched fetching in the {@link CentralizedMessageFetcher}.<br>
     * Default value is {@code false}: every poll uses per-queue fetching, whatever the active queue count.<br>
     * <br>
     * Batched fetching collapses one query per active queue into a single query across all of them. The
     * queue-fetch-strategy benchmark found this to pay off above roughly four active queues - see
     * {@code BENCHMARK-queue-fetch-strategy.md} and {@link #setBatchedFetchSwitchThreshold(int)}.<br>
     * <br>
     * Note that the two strategies do not select identical messages: per-queue fetching is ordered-priority,
     * whereas batched fetching selects the oldest eligible messages regardless of delivery mode.
     *
     * @param useBatchedFetch whether the centralized fetcher may use batched fetching
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setUseBatchedFetch(boolean useBatchedFetch) {
        this.useBatchedFetch = useBatchedFetch;
        return this;
    }

    /**
     * Set the active queue-count threshold for switching from per-queue fetch to batched fetch
     * in the {@link CentralizedMessageFetcher}.<br>
     * Only consulted when batched fetching has been enabled via {@link #setUseBatchedFetch(boolean)}.<br>
     * Default value is {@code 4}, the point at which the queue-fetch-strategy benchmark showed batched
     * fetching starting to win.
     *
     * @param batchedFetchSwitchThreshold threshold: per-queue fetch for queue counts <= threshold, batched fetch above threshold
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setBatchedFetchSwitchThreshold(int batchedFetchSwitchThreshold) {
        this.batchedFetchSwitchThreshold = batchedFetchSwitchThreshold;
        return this;
    }

    /**
     * Coalesce acknowledgements so a batch of handled messages costs one transaction instead of one each.
     * Only applies when the {@link CentralizedMessageFetcher} is in use.
     * <p>
     * <b>Not a throughput feature, despite the number attached to it historically.</b> One transaction per
     * acknowledgement measured 16.5x against one per batch <em>in a raw-SQL harness</em>, and that does not
     * reproduce here: through the component it is <b>1.02x</b> on a backlog drain and <b>1.00x</b> in steady state
     * with a worse p99. Once a connection pool and a real consumer are in the picture the acknowledgement
     * transaction is not the bottleneck. See {@code docs/durable-queues-measurements.md} §2.
     * <p>
     * Off by default, because it is a semantic change and not only a faster one: an acknowledgement can sit
     * buffered for up to {@link #setAcknowledgementFlushInterval(Duration)}, so a crash in that window
     * redelivers messages that were in fact handled. At-least-once already permits this and handlers are
     * required to be idempotent, but the window widens, so a deployment should choose it rather than inherit
     * it from an upgrade.
     * <p>
     * Requires {@link TransactionalMode#SingleOperationTransaction} — the recovery path the buffer depends on
     * does not exist under {@link TransactionalMode#FullyTransactional}, and {@code build()} will reject the
     * combination. {@link QueuedMessage.DeliveryMode#IN_ORDER} messages are never buffered regardless of this
     * setting; the per-key barrier reads completion from row absence, so deferring their acknowledgement
     * stalls the key and measured 0.82x.
     *
     * @param useBatchedAcknowledgement whether to coalesce acknowledgements
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setUseBatchedAcknowledgement(boolean useBatchedAcknowledgement) {
        this.useBatchedAcknowledgement = useBatchedAcknowledgement;
        return this;
    }

    /**
     * Flush the acknowledgement buffer once this many acknowledgements are pending. Only consulted when
     * {@link #setUseBatchedAcknowledgement(boolean)} is {@code true}.
     *
     * @param acknowledgementMaxBatchSize the batch size at which a flush is triggered
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setAcknowledgementMaxBatchSize(int acknowledgementMaxBatchSize) {
        this.acknowledgementMaxBatchSize = acknowledgementMaxBatchSize;
        return this;
    }

    /**
     * Flush the acknowledgement buffer at least this often, so a trickle of messages is not left buffered.
     * Only consulted when {@link #setUseBatchedAcknowledgement(boolean)} is {@code true}.
     * <p>
     * Must stay well below the {@code messageHandlingTimeout}, or {@code resetMessagesStuckBeingDelivered}
     * can resurrect a message whose acknowledgement is merely buffered and deliver it twice. The value is
     * validated against that timeout on construction rather than trusted.
     *
     * @param acknowledgementFlushInterval the maximum time an acknowledgement may sit buffered
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setAcknowledgementFlushInterval(Duration acknowledgementFlushInterval) {
        this.acknowledgementFlushInterval = acknowledgementFlushInterval;
        return this;
    }
    /**
     * What to do when two {@link OrderedMessage}s share a key and an order. Defaults to
     * {@link OrderedMessageDuplicateStrategy#REJECT}, which adds a unique index over
     * {@code (queue_name, key, key_order)} for ordered messages.
     * <p>
     * The default is safe for every ordered message the framework itself produces - the event processors and the
     * subscription manager all key on the aggregate id and order by {@code EventOrder}, which is unique within its
     * stream. It bites only on application code deriving the order from something not unique, where rejecting is
     * the correct outcome because the alternative is ordered delivery that is not ordered.
     * <p>
     * <b>On an existing table containing duplicates, startup fails</b> with a message naming them, rather than
     * running unprotected. Set {@link OrderedMessageDuplicateStrategy#ALLOW} to keep the previous behaviour.
     *
     * @param orderedMessageDuplicateStrategy the strategy to apply
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setOrderedMessageDuplicateStrategy(OrderedMessageDuplicateStrategy orderedMessageDuplicateStrategy) {
        this.orderedMessageDuplicateStrategy = orderedMessageDuplicateStrategy;
        return this;
    }

    /**
     * Set warning threshold for batched fetch raw result size.
     *
     * @param batchedFetchWarnRowsThreshold warning threshold for raw rows returned from batched fetch
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setBatchedFetchWarnRowsThreshold(int batchedFetchWarnRowsThreshold) {
        this.batchedFetchWarnRowsThreshold = batchedFetchWarnRowsThreshold;
        return this;
    }

    /**
     * Sets whether to use the ordered/unordered query optimization for message fetching. When {@code true}
     * (the default) separate fetch queries and partial indexes are used for ordered and unordered messages;
     * when {@code false} a single unified query serves both.
     * <p>
     * Leave this on unless you have a measured reason not to. The unified query applies the ordered per-key
     * barrier to every candidate row, including unordered ones that cannot need it, which measured 5.4x
     * slower on a backlog containing both kinds. Pure-ordered traffic is indifferent, since it needs the
     * barrier either way. See {@code docs/durable-queues-measurements.md}.
     *
     * @param useOrderedUnorderedQuery flag to enable/disable the query optimization
     * @return this builder instance
     */
    public PostgresqlDurableQueuesBuilder setUseOrderedUnorderedQuery(boolean useOrderedUnorderedQuery) {
        this.useOrderedUnorderedQuery = useOrderedUnorderedQuery;
        return this;
    }

    @SuppressWarnings("removal")

    /**
     * Observes how each delivery ended - handled, retried, dead-lettered - for delivery statistics and
     * observability. Off by default ({@link DurableQueueMessageObserver#none()}).
     * <p>
     * This is how {@code InMemoryDurableQueuesStatistics} is wired: pass its {@code observer()}. Note the
     * direction - the statistics object is created first and handed here, rather than the queue being handed to
     * the statistics, which is what the trigger-based implementation needed and why enabling statistics used to
     * mean running DDL against the queue table.
     *
     * @param messageObserver the observer, wrapped in {@link DurableQueueMessageObserver#safe} by the constructor
     */
    public PostgresqlDurableQueuesBuilder setMessageObserver(DurableQueueMessageObserver messageObserver) {
        this.messageObserver = messageObserver != null ? messageObserver : DurableQueueMessageObserver.none();
        return this;
    }

    /**
     * <b>Experimental, opt-in:</b> replace the ordered per-key barrier with a per-key cursor (default false).
     * <p>
     * The barrier evaluates a correlated {@code NOT EXISTS (… key_order < mine)} against every candidate row, so
     * its claim cost scales with the <b>backlog</b> and it can only ever yield a key's single head. The cursor
     * drives from a key-state table - one row per {@code (queue_name, key)} carrying {@code completed_through} -
     * so the cost scales with the number of <b>keys</b>. In the barrier's pathological regime (few keys, deep
     * backlog: 8 keys × 2 500 messages) it measures <b>1.81×</b> on drain through the component, and that figure
     * is unchanged by {@code ANALYZE}, so it is a property of the barrier rather than of missing statistics. With
     * shallow keys it is 1.02-1.05x - not worth having - and in steady state, where the queue keeps up, it is
     * parity. A prototype measured the <em>claim phase alone</em> at 217×; that is not what a deployment sees.
     * <p>
     * It exists to be <b>measured</b> against real traffic, which is why it is a flag rather than a replacement.
     *
     * <h2>What switching it on does</h2>
     * Creates {@code <queueTable>_key_cursor} and a non-partial {@code (queue_name, key, key_order)} index on the
     * queue table, creates a cursor row on every ordered enqueue, and rewrites the ordered claim and the
     * acknowledgement. Unordered traffic is untouched.
     *
     * <h2>Rolling deploys are safe, and that is measured</h2>
     * Barrier instances and cursor instances can share one table (27 consecutive runs with a negative control):
     * both key off the same physical rows, and the only unshared state - {@code completed_through} - can go
     * stale-low, which the design tolerates. Rollback is equally safe. A barrier instance enqueuing ordered
     * messages creates no cursor rows, so those keys would be invisible to cursor instances; an empty ordered
     * claim triggers a bounded, idempotent reconcile that closes exactly that window.
     *
     * @param useOrderedMessageCursor whether to use the per-key cursor for ordered messages
     */
    public PostgresqlDurableQueuesBuilder setUseOrderedMessageCursor(boolean useOrderedMessageCursor) {
        this.useOrderedMessageCursor = useOrderedMessageCursor;
        return this;
    }

    public PostgresqlDurableQueues build() {
        return new PostgresqlDurableQueues(unitOfWorkFactory,
                                           jsonSerializer != null ? jsonSerializer : DurableQueuesSerialization.createDefaultJSONSerializer(),
                                           sharedQueueTableName,
                                           multiTableChangeListener,
                                           queuePollingOptimizerFactory,
                                           transactionalMode,
                                           messageHandlingTimeout,
                                           useCentralizedMessageFetcher,
                                           centralizedMessageFetcherPollingInterval,
                                           centralizedQueuePollingOptimizerFactory,
                                           useOrderedUnorderedQuery,
                                           useBatchedFetch,
                                           batchedFetchSwitchThreshold,
                                           batchedFetchWarnRowsThreshold,
                                           new BatchedAcknowledgementSettings(useBatchedAcknowledgement,
                                                                              acknowledgementMaxBatchSize,
                                                                              acknowledgementFlushInterval),
                                           orderedMessageDuplicateStrategy,
                                           PostgresqlDurableQueues.Role.STANDALONE,
                                           messageObserver,
                                           useOrderedMessageCursor);
    }
}
